version: "3.1"
services:
  migrate:
    image: migrate
    build:
      context: .
      dockerfile: migrate.Dockerfile
    volumes:
      - './migrations:/migrations'
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [ "goose", "-dir", "/migrations", "postgres", "host=postgres user=postgres password=postgres dbname=social sslmode=disable", "up" ]

  app:
    image: social
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

  upload:
    image: upload
    build:
      context: .
      dockerfile: upload.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
