version: "3.1"
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  app:
    depends_on:
      - postgres
    image: social
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile


volumes:
  postgres_data: