{
 "title": "NewJmeter",
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  {
   "title": "Threads",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jsr223_rt_as_summary{code=\"200\"}",
     "legendFormat": "{{label}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(jsr223_count_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(jsr223_rsize_as_hist_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}