global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'jmeter'
    static_configs:
      - targets: [ 'host.docker.internal:9270' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
#      - targets: [ '192.168.0.183:8080' ]

#      - targets:
#          - cadvisor:8080