GET http://localhost:8080/user/search?first_name=Ан&last_name=По
Content-Type: application/json

###

GET http://localhost:8080/user/get/40aeb475-da6d-49ca-9276-728e6463751f
Content-Type: application/json

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "id": "2bf1fff0-584c-4a26-92eb-b64d526501da",
  "password": "test"
}

> {% client.global.set("auth_token", response.body.token); %}


###
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "first_name": "Andrey",
  "password": "test"
}


###
GET http://localhost:8080/post/feed
Authorization: Bearer {{auth_token}}